In [ ]:
import cv2
import numpy as np

In [ ]:
parkourX0 = 0
parkourX1 = 0

parkourY0 = 0
parkourY1 = 0

In [ ]:
img = cv2.imread('/home/mohamed/star.jpg',0)
ret,thresh = cv2.threshold(img,127,255,0)
contours,hierarchy, rest = cv2.findContours(thresh, 1, 2)
cnt = contours[0]
M = cv2.moments(cnt)
print M

In [ ]:
x,y,w,h = cv2.boundingRect(cnt)
cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

In [ ]:
im = cv2.imread('/home/mohamed/star.jpg')
gray=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
contours,hierarchy, rest = cv2.findContours(gray,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
idx =0 
for cnt in contours:
    idx += 1
    x,y,w,h = cv2.boundingRect(cnt)
    roi=im[y:y+h,x:x+w]
    cv2.imwrite(str(idx) + '.jpg', roi)
    #cv2.rectangle(im,(x,y),(x+w,y+h),(200,0,0),2)
cv2.imshow('img',im)
cv2.waitKey(0)  

In [ ]:
from __future__ import print_function
import cv2 as cv
import numpy as np
import argparse
import random as rng
rng.seed(12345)

input_src = "/home/mohamed/Downloads/scaledMap.png"
def thresh_callback(val):
    threshold = val
    
    canny_output = cv.Canny(src_gray, threshold, threshold * 2)
    print(canny_output)
    
    _, contours, _ = cv.findContours(canny_output, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
    
    
    contours_poly = [None]*len(contours)
    boundRect = [None]*len(contours)
    centers = [None]*len(contours)
    radius = [None]*len(contours)
    for i, c in enumerate(contours):
        contours_poly[i] = cv.approxPolyDP(c, 3, True)
        boundRect[i] = cv.boundingRect(contours_poly[i])
        centers[i], radius[i] = cv.minEnclosingCircle(contours_poly[i])
    
    
    drawing = np.zeros((canny_output.shape[0], canny_output.shape[1], 3), dtype=np.uint8)
    
    
    for i in range(len(contours)):
        color = (rng.randint(0,256), rng.randint(0,256), rng.randint(0,256))
        cv.drawContours(drawing, contours_poly, i, color)
        cv.rectangle(drawing, (int(boundRect[i][0]), int(boundRect[i][1])), \
          (int(boundRect[i][0]+boundRect[i][2]), int(boundRect[i][1]+boundRect[i][3])), color, 2)
        cv.circle(drawing, (int(centers[i][0]), int(centers[i][1])), int(radius[i]), color, 2)
    
    
    cv.imshow('Contours', drawing)

src = cv.imread(input_src)
if src is None:
    print('Could not open or find the image:', input_src)
    exit(0)
# Convert image to gray and blur it
src_gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
src_gray = cv.blur(src_gray, (3,3))
source_window = 'Source'
cv.namedWindow(source_window)
cv.imshow(source_window, src)
max_thresh = 255
thresh = 50 # initial threshold
cv.createTrackbar('Canny thresh:', source_window, thresh, max_thresh, thresh_callback)
thresh_callback(thresh)
cv.waitKey()

In [ ]:
img = cv2.imread('/home/mohamed/road_small')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
ret,thresh = cv2.threshold(gray,127,255,1)
 
_, contours, _ = cv2.findContours(thresh,1,2)

In [ ]:
import cv2
import numpy as np
 
image = cv2.imread("/home/mohamed/road_small")
copy = image.copy()
 
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray', gray)
cv2.waitKey(0)
 
edged = cv2.Canny(gray, 10, 250)
cv2.imshow('Edged', edged)
cv2.waitKey(0)
 
kernel = np.ones((5, 5), np.uint8)
 
dilation = cv2.dilate(edged, kernel, iterations=1)
cv2.imshow('Dilation', dilation)
cv2.waitKey(0)
 
closing = cv2.morphologyEx(dilation, cv2.MORPH_CLOSE, kernel)
cv2.imshow('Closing', closing)
cv2.waitKey(0)
 
(image, cnts, hiers) = cv2.findContours(closing, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
 
cont = cv2.drawContours(copy, cnts, -1, (0, 0, 0), 1, cv2.LINE_AA)
cv2.imshow('Contours', cont)
cv2.waitKey(0)
 
mask = np.zeros(cont.shape[:2], dtype="uint8") * 255
 
# Draw the contours on the mask
cv2.drawContours(mask, cnts, -1, (255, 255, 255), -1)
 
# remove the contours from the image and show the resulting images
img = cv2.bitwise_and(cont, cont, mask=mask)
cv2.imshow("Mask", img)
cv2.waitKey(0)
 
for c in cnts:
    x, y, w, h = cv2.boundingRect(c)
    if w > 50 and h > 130:
        new_img = img[y:y + h, x:x + w]
 
        cv2.imwrite('Cropped.png', new_img)
        cv2.imshow("Cropped", new_img)
        cv2.waitKey(0)

In [ ]:
import cv2
import numpy as np

filename = '/home/mohamed/road_small'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

gray = np.float32(gray)
dst = cv2.cornerHarris(gray,10,3,0.04)

#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.01*dst.max()]=[0,0,255]

cv2.imshow('dst',img)
if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

image = cv2.imread("/home/mohamed/rollover_gold_00235.jpg")
copy = image.copy()

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blur = cv2.blur(gray, (3,3))
edged = cv2.Canny(blur, 10, 250)
(image, cnts, hiers) = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

biggest_cnt = -1
biggest_cnt_size = -1
for c in cnts:
    if (c.size > biggest_cnt_size):
        biggest_cnt_size = c.size
        biggest_cnt = c

hull = cv2.convexHull(biggest_cnt)
approx = cv2.approxPolyDP(hull,20,True)

cont = cv2.drawContours(copy, [approx], 0, (0,0,0), 3)
cv2.imshow('Contours', cont)
cv2.waitKey(0)
approx

In [ ]:
from __future__ import division

height_tiles = 5
width_tiles = 4

import numpy as np
import cv2
img = cv2.imread('/home/mohamed/Downloads/scaledMap.png')
height, width, _ = img.shape

test_input = (533, 200)

test_output = (test_input[0] * height_tiles / height, test_input[1] * width_tiles / width)
test_output

In [ ]:
img = cv2.imread('/home/mohamed/Downloads/scaledMap.png')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)

lines = cv2.HoughLines(edges,1,np.pi/180,200)
for rho,theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imwrite('houghlines3.jpg',img)

In [ ]:
import numpy as np
import cv2

img = cv2.imread('/home/mohamed/rollover_gold_00235.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)
minLineLength = 10
maxLineGap = 20
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength,maxLineGap)
for onelines in lines:
    for x1,y1,x2,y2 in onelines:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('houghlines5.jpg',img)

[[  7.28597450e-01   3.06133382e-03  -9.49931885e+00]
 [  3.16077729e-18   7.00280112e-01  -6.30252101e+00]]
[ 111.75399121  230.39215686]
[[  1.37250000e+00  -6.00000000e-03   1.30000000e+01]
 [ -6.19490224e-18   1.42800000e+00   9.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
[ 164.99999999  338.            1.        ]
[[  8.66257376e-01   3.63973688e-03  -1.12941035e+01]
 [  2.58473798e-16   5.37266059e-01  -4.83539453e+00]
 [  3.41420777e-04  -3.26691945e-04   1.00000000e+00]]
